import config from '../Config';

const API_URL = config.apiUrl;

export default {
  STATIC_API_CALL: false,
  CHAT_BOT: true,
  USER_ROLES: {
    ACCOUNT_OWNER: 'AccountOwner',
    ACCOUNT_ADMIN: 'AccountAdmin',
    AD_USER: 'ADUser',
    ACCOUNT_HOLDER_USER: 'AccountHolder',
  },
  API: {
    BASEURL: {
      URL: API_URL,
    },

    PASSWORD: {
      CREATE_PASSWORD: 'user/api/user/user/all',
      SET_USER_PROFILE: 'user/api/user/User/profile',
    },

    SEARCH_RESULT: {
      GET_SEARCH_RESULT: 'fulltextsearch/api/fulltextsearch/search/search/',
      GET_AUTO_POPULATE_RESULT:
        'fulltextsearch/api/fulltextsearch/search/suggest/',
    },

    USER: {
      GET_PULSE_MAP_CONTENT: 'common/api/common/heatmap  ',
      GET_USER_PROFILE: 'user/api/user/user/keycloakid/',
      UPDATE_USER_PROFILE: 'user/api/user/User/profile/',
      UPLOAD_PROFILE_PIC: `${API_URL}document/api/file/upload`,
      ADD_COWORKERS: 'user/api/user/user/coworker',
      COWORKERS_LIST: 'user/api/user/User/coworker/coworkerslist/',
      GET_INDUSTRY_LIST: 'user/api/industry/all',
      GET_COMPANY_LIST: 'user/api/company/all?skipPagination=true',
      DELETE_USER: 'user/api/user/User/',
      UPDATE_LAST_LOGIN: 'user/api/user/user/lastlogin/',
      INTERNAL_USER: 'user/api/internaluser',
      GET_PRIMARY_USER: 'user/api/user/user/company/primaryuser/',
      DELETE_PROFILE_PIC: 'document/api/file/',
      UPDATE_EMPLOYEE_INFO: 'user/api/user/user/employeecountry/',
      GET_COMPANY_COUNTRIES: 'user/api/user/user/employeecountry/',
      GET_ACCOUNT_USER_COUNT: 'user/api/user/admin/totalCount',
    },
    COUNTRY: {
      GET_COUNTRY_LIST: 'common/api/common/country/all',
      GET_ALL_COUNTRY_INFO_LIST: 'content/api/content/snapshot/allcountry',
      GET_REGION_LIST: 'common/api/common/region/all',
      GET_SPECIFIC_REGION_LIST: 'common/api/common/country/all',
      GET_FAVOURITE_COUNTRY: 'user/api/user/user/employeecountry/',

      CREATE_NEW_COUNTRY: 'common/api/common/country',
      UPDATE_COUNTRY_BY_ID: 'common/api/common/country/',
      ADD_NEW_COUNTRY_BY_ID: 'common/api/common/country',
      UPDATE_COUNTRY_STATUS:
        'common/api/common/Country/activate/{country_id}?active=',
      FILE_UPLOAD: 'document/api/file/upload',
      GET_USER_COUNTRY: 'user/api/user/user/employeecountry/',
      GET_EMPLOYEE_TYPE: 'user/api/user/User/emloyeetype',
      GET_EMPLOYEE_COUNTRY: 'user/api/user/user/employeecountry/',
      PDF_CREATE: 'pdfcreator/api/pdfcreator/createpdf/',
      GET_ALL_TOPIC: 'pdfcreator/api/pdfcreator/createpdf/',
      ADD_COUNTRY: 'user/api/user/user/usercountry',
      GET_FLAG_DOWNLOAD: `${API_URL}document/api/file/download/`,
      DELETE_COUNTRY: 'user/api/user/user/usercountry/',
      PUBLIC_HOLIDAYS: 'content/api/HolidayCalendar/publicholidays',
      GET_EMPLOYEE_LIFECYCLE: 'content/api/content/allsolutions?listcount=5',
      ADD_SINGLE_FAV_COUNTRY: 'user/api/user/user/usercountry/',
      GET_HOLIDAY_LIST: 'content/api/HolidayCalendar/publicholidays/',
      GET_EMPLOYEE_COUNT_LIST: 'user/api/user/user/employeecountlist/',
    },
    STATE: {
      GET_STATE_LIST: 'common/api/common/state/all/',
    },
    SUPER_ADMIN_USER: {
      ADD_SUPER_ADMIN: 'user/api/user/User',
      UPDATE_SUPER_ADMIN: 'user/api/user/User/',
      GET_ADMINISTRATOR_ROLE: 'user/api/user/user/role',
      GET_USER_LIST: 'user/api/user/Admin/listing',
      CHANGE_USER_STATUS: 'user/api/user/User/activate/',
      SEND_EMAIL_TO_CHANGE_STATUS: 'user/api/user/user/activation/',
      GET_USER_INFO: 'user/api/user/User/',
      ADD_EDIT_USER_INFO: 'user/api/accountuser/',
      GET_ACCOUNT_USER_LIST_BY_COMPANY: 'user/api/user/user/accountusers/'
    },

    USER_ACCOUNTS: {
      ADD_ACCOUNT: 'user/api/company',
      UPDATE_ACCOUNT: 'user/api/company/',
      GET_ACCOUNT_LIST: 'user/api/company/all',
      UPDATE_ACCOUNT_STATUS: 'user/api/company/{id}/activate/',
      GET_ACCOUNT_INFO_BY_ID: 'user/api/company/',
      GET_INDUSTRY_LIST: 'user/api/industry/all',
    },

    HOME: {
      GET_COUNTRY_LIST: 'user/api/user/User/usercountry/',
      GET_POPULAR_COUNTRIES: 'content/api/content/allsolutions',
      GET_SUPER_TOPICS: 'content/api/Content/supertopic/solution',
      GET_SUPER_TOPIC_TAG: 'content/api/content/supertopics',
      GET_ALERT: 'content/api/Content/alerts/',
      GET_SOLUTION: 'content/api/Content/Published/solution',
    },
    DETAILS: {
      GET_ALERTS_LIST: 'content/api/Content/alerts/',
      GET_SUPER_TOPICS: 'content/api/Content/snapshot',
      GET_COUNTRY_DETAISL: 'common/api/common/country',
      GET_SPECIFICS_DATA: 'content/api/Content/Published/solution',
      GET_PUBLISHED_SOLUTION: 'content/api/Content/Published/solution',
      GET_COUNTRY_BULLETCHART: 'common/api/common/indicators',
      VIEWED_ALERT: '/user/api/useraudit/alerts/add',
    },
    ROLES: {
      GET_ROLES_LIST: 'user/api/role/all',
      GET_USERS_FEAT: 'user/api/role/features',
      GET_USER_GROUP: 'user/api/role/usergroups',
      POST_USER_DATA: 'user/api/role',
    },
    KNOWLEDGE_BASE: {
      GET_ARTICLE_DETAILS: 'user/api/role/all',
      GET_INSIGHTS_LIST: 'user/api/role/features',
      GET_ARTICLES: 'content/api/content/articles',

      GET_ALL_FAQS: 'content/api/content/articles',
      GET_FEATURED_ARTICLES: 'content/api/content/articles',
      GET_QUICK_LINKS: 'user/api/role/features',
      GET_TAGS: 'user/api/role/features',
    },
    SUBSCRIPTION: {
      GET_ALL_LIST: '/license/api/Subscription/all',
      GET_FEAT_LIST: '/license/api/Subscription/features',
      POST_DATA: 'license/api/subscription',
      GET: 'license/api/Subscription',
    },
    HR_TEMPLATE: {
      GET_ALL_PURCHASED_DOCUMENT_LIST: 'purchase/api/purchase/cart/useritems',
      GET_ALL_DOCUMENT_LIST: 'document/api/document/template/all',
      GET_CART_DETAILS: 'purchase/api/purchase/cart/',
      GET_LANGUAGE_LIST: 'common/api/common/language/all',
      GET_ALL_CATEGORY_LIST: 'document/api/documentcategory/all',
      GET_ALL_DOCUMENTS: 'document/api/documentcategory/all',
      GET_ALL_TEMPLATES: 'document/api/document/template/all/',
      GET_ALL_LANGUAGE: 'common/api/common/language/all/', // ?showInactive=false&showDeleted=false
      GET_ALL_COUNTRIES: 'common/api/common/country/all',
      ADD_NEW_TEMPLATE: 'document/api/document/',
      UPDATE_TEMPLATE: 'document/api/document/',
      ADD_TO_ARCHIVES: 'document/api/document/',
      DELETE_TEMPLATE: 'document/api/document/',
      DEACTIVATE_TEMPLATE: 'document/api/document/{id}/activate?active=',
      ADD_NEW_LANGUAGE: 'common/api/common/language',
      ADD_NEW_TEMPLATE_TYPE: 'document/api/documentcategory',
      CHECKOUT_CART: 'purchase/api/purchase/cart/checkout',
      PAYMENT_API: 'payment/api/payment/create',
      ADD_TO_CART: 'purchase/api/purchase/cart/',
      ORDER_PREVIEW: 'purchase/api/purchase/cart/orderpreview/',
      // ORDER_PREVIEW: 'https://cd24906b-3eea-4174-94f2-eb17b3684815.mock.pstmn.io//api/purchase/cart/orderpreview',
      DELETE_CART_ITEM: 'purchase/api/purchase/cart/removeitem/',
      ASK_QUESTION_POP_UP: 'user/api/expert/postquestion',
      GET_PREVIEW_DETAILS: 'document/api/file/download/',
      DOWNLOAD_PREVIEW_FILE: `${API_URL}document/api/file/download/`,
      PAYMENT_FAILED_API: "purchase/api/purchase/cart/revertcheckout",
      GET_TEMPLATE: "document/api/document/",
      SAVE_CREDIT_CARD: "payment/api/customer/paymentprofile",
      GET_SAVED_CREDIT_CARD: "payment/api/customer/",
      DELETE_SAVED_CARD: "payment/api/customer/deleteprofile",
      PAYMENT_SAVED_CARD: "payment/api/payment/chargeCustomer",
      EMAIL_PURCHASE_DETAILS: "notification/api/email/ordercomplete",
      DOWNLOAD_INVOICE_HR_TEMPLATE: "PdfCreator/api/pdfcreator/downloadinvoice"

    },
    PURCHASE_EXPERT_BRIEFS: {
      GET_EXPERT_LIST: 'user/api/expert/briefs',
      GET_PURCHASE_LIST: 'purchase/api/purchase/cart/purchasehistory/',
      GET_MANAGE_BRIEFS_LIST: 'user/api/expert/briefs',
      SAVE_TIME_TRACKER_DETAILS: 'user/api/Expert/timetracker',
      VIEW_QUERY_DETAILS: 'user/api/expert/query/',
      GET_MANAGE_QUERY_DETAILS: 'user/api/Expert/managequery/query/',
      UPLOAD_DOCUMENT: 'user/api/Expert/queryuploads',
      DELETE_DOCUMENT: 'user/api/Expert/queryuploads/',
      GET_EXPERT_EMAIL_LIST: 'user/api/expert/emails/',
      ASSIGN_TO_EXPERT: 'user/api/Expert/assignexpert/',
      NOTE_FOR_INTERNAL_VIEW: 'user/api/Expert/managequery/internalnote',
      ADD_ESTIMATION: 'user/api/expert/estimate/add',
      UPDATE_ESTIMATE: 'user/api/Expert/estimate/update',
      GET_ESTIMATE_DETAILS: "user/api/expert/queryestimate/",
      UPDATE_STATUS: "user/api/expert/estimate/updatestatus",
      GET_QUERY_DETAILS: "user/api/expert/query/",
      GET_STATUS_QUERY: "user/api/Expert/managequery/query/",
      GET_QUERY_SUMNMERY: "user/api/Expert/querysummary",
      GET_EXPERT_HOURS: 'user/api/Expert/experthour',
      DOWNLOAD_EXPERT_BRIEFS: 'user/api/expert/brief/',
      GET_QUERY_STATUS: 'user/api/expert/querystatuses',
      DOWNLOAD_MANAGE_BRIEFS_FILE: 'user/api/expert/download/experthour',
      DOWNLOAD_SINGLE_FILE: 'user/api/Expert/querysummaryfile/'
    },
    ADD_MORE_HOURS: {
      ADD_TO_CART: 'purchase/api/purchase/cart/',
      EXPERT_HOUR: 'purchase/api/purchase/Product/all/expert-hour',
      ADD_HOURS: '/user/api/expert/hours/add',
    },
    ALERTS: {
      GET_ALL_ALERTS: 'alert/api/alert/all',
      GET_COUNTRIES_ALERTS: 'alert/api/alert/all',
      GET_GENERAL_ALERTS: '',
      GET_UNREAD_ALERTS: '',
      GET_MARK_AS_READ: 'alert/api/alert/',
      DELETE_ALERTS: 'alert/api/alert/',
    },
    MANAGE_ALERTS: {
      GET_ACCOUNT_LIST: 'user/api/company/all',
      GET_USER_LIST: '/user/api/user/user/accountusers/',
      ADD_QUERY: '/user/api/expert/addquery',
      GET_ALERT_TYPES_LIST: 'alert/api/alert/NotificationSettings',
      UPDATE_ALERT: 'alert/api/alert/NotificationSettings'

    }
  },
  IMAGE: {
    DOWNLOAD: `${API_URL}document/api/file/download/`,
  },
  STORAGE: {
    AUTH: {
      TOKEN: 'auth-token',
      ACCOUNT_DATA: 'account-data',
      USER_DATA: 'user-data',
      KEY_CLOCK_TOKEN: 'key-clock-token',
      COUNTRY_DATA: 'country-data',
      KEY_CLOCK_USER_ID: 'key-clock-user-id',
      USER_PORFILE: 'user-profile',
      ABOUT_YOU: 'about-you',
      COUNTRY_SELECTION: 'country-selection',
      EMPLOYEE_INFO: 'employee-info',
      ADD_USER: 'add-user',
      LAST_LOGIN_ATTEMPTED: 'exp_last_login',
      KEY_CLOCK_ID: 'key_clock_id',
    },
  },
  ROUTE: {
    SIDEBAR: {
      HOME: '/home',
      SETTINGS: {
        USERLIST: '/settings/users',
        USER_LIST_BY_PAGE: '/settings/users/:pageName',
        ADD_USER: '/settings/users/add-user',
        ADD_USER_ACCOUNTS: '/settings/accounts/add-user/:company',
        SEARCH_PAGE: '/settings/search/result',
        EDIT_USER: '/settings/users/edit-user/',
        EDIT_USER_BY_ID: '/settings/users/edit-user/:id',
        ADD_ROLE: '/settings/roles',
        COUNTRY_CONFIGURATION: '/country-configuration',
        COUNTRY_CONFIGURATION_VIEW: '/country-configuration-view',
        MY_ACCOUNT: '/settings/my-account',
        FAVORITE_COUNTRIES: '/favorite-countries',
        ADD_COUNTRY: '/settings/add-country',
        ADD_ACCOUNT: '/settings/add-account',
        EDIT_ACCOUNT: '/settings/edit-account/:id',
        REACTIVATE_ACCOUNT: '/settings/reactivate-account/:id',
        VIEW_ACCOUNT: '/settings/view-account/:id',
        PURCHASES: '/settings/purchases',
        EXPERT_BRIEFS: '/settings/expert-briefs',
        USERS: '/settings/account-users',
        USER_ADD_EDIT: '/settings/account-user/:id',
        PURCHASE_EXPERT_BRIEFS: '/settings/purchases-expert-briefs',
        PURCHASE_EXPERT_BRIEFS_BY_PAGE: '/settings/purchases-expert-briefs/:pageName',
        FOURM_HOME: '/client/forum',
        EGSFOURM_HOME: '/internal/forum',
        MANAGE_BRIEFS: '/settings/manage-briefs',
        MANAGE_QUERY: '/settings/manage-query/',
        MANAGE_QUERY_BY_ID: '/settings/manage-query/:id',
        VIEW_QUERY: '/settings/view-query/',
        VIEW_QUERY_BY_ID: '/settings/view-query/:id',
        CLIENT_VIEW_ESTIMATE: '/settings/purchases-expert-briefs/view-estimate',
        CLIENT_VIEW_ESTIMATE_BY_ID: '/settings/purchases-expert-briefs/view-estimate/:refNo/:id',
        CLIENT_VIEW_QUERY: '/settings/purchases-expert-briefs/view-query',
        CLIENT_VIEW_QUERY_BY_ID: '/settings/purchases-expert-briefs/view-query/:refNo/:id',
        ADD_QUERY: '/settings/add-query',
        PEOPLE_ANALYTICS: '/settings/people-analytics'
      },
      KNOWLEDGE_BASE: {
        HOME: '/knowledge-base',
      },
    },
    USER: {
      ADD_USER: '/add-user',
      USER_PROFILE: '/userProfile',
      USER_PROFILE_HASH: '/:id/',
      INITIAL_PAGE: '/',
    },
    REGISTRATION_FLOW: {
      EMPLOYEE_INFORMATION: '/employee-information',
    },
    COUNTRY: {
      COUNTRY: '/country',
      ALL_COUNTRY: '/all-country',
      UN_FAVORITE_COUNTRIES: '/unfavorite-countries/:id',
    },
    LOCATION: {
      LOCATION: '/location',
    },
    SUCCESS: {
      SUCCESS: '/success',
    },
    PASSWORD: {
      WELCOME: '/welcome',
    },
    HOME_PAGE: {
      HOME: '/home',
    },
    DETAILS_PAGE: {
      DETAILS: '/details/:id',
      DETAILS_ID: '/details/',
      CUSTOM_HOME_DETAILS: '/details/:country/:id',
      CUSTOM_UN_FAV_COUNTRY_DETAILS: '/unfavorite-countries/:country/:id',
      CUSTOM_UN_FAV_COUNTRY_DETAILS_BY_ID: '/unfavorite-countries/',
    },
    COUNTRY_COMPARE: {
      COMPARE: '/CountryCompare',
    },
    ROLES_PAGE: {
      ROLES: '/roles',
      CREATE_ROLES: '/create-role',
      VIEW_ROLES: '/view-role/:id',
      EDIT_ROLES: '/edit-role/:id',
    },
    KNOWLEDGE_BASE: {
      HOME: '/knowledge-base',
      INSIGHTS_ANALYSIS: '/insights-and-analysis',
      INSIGHTS_ANALYSIS_Name: '/insights-and-analysis/:id/:country/:regionId',
      ARTICLE_LANDING: '/article-details',
      ARTICLE_PAGE: '/article-page', //newly created
      ARTICLE_PAGE_Name: '/article-page/:name',
      ARTICLE_PAGE_Country_Name: '/article-page/:id/:country/:name',
      FAQ: '/frequently-asked',
      ALERTS_COUNTRY_PAGE: '/knowledge-base/:country/alerts',
      ALERTS_HOME_PAGE: '/knowledge-base/alerts',
      MANAGE_ALERTS: '/knowledge-base/manage-alerts',
      PRODUCT_UPDATES: '/product-updates'
    },
    SUBSCRIPTIONS: '/subscriptions',
    HR_TEMPLATE: {
      LIST: '/upload-hr-template',
      ADD_NEW_TEMPLATE: '/upload-hr-template/add-new-template',
      VIEW_EDIT_NEW_TEMPLATE: '/upload-hr-template/edit-template/:id/:status',
      ARCHIVE: '/archive-hr-template',
    },
    SUBSCRIPTION_PAGE: {
      ALL: '/subscription-list',
      CREATE: '/create-subscription',
      EDIT: '/edit-subscription/:id',
      VIEW: '/view-subscription/:id',
    },
    HR_TEMPLATE_PAGE: {
      DOC_SHOP: '/doc-shop',
      IN_YOUR_CART: '/your-cart',
      REVIEW_PAYMENT: '/review-and-pay',
      PAYMENT_SUCCESS: '/payment-success',
      PAYMENT_FAILED: '/payment-failed',
      PAYMENT_SUCCESS_Name: '/payment-success/:name',
      CONFIRM_PAYMENT: "/confirm-payment"
    },
    BUY_MORE_HOURS: {
      REVIEW_PAYMENT: '/buy-more-hours-review-and-pay'
    }
  },
  PERMISSION_MAPPING: {
    PURCHASE_ADDITIONAL_CONSULTING_HOURS:
      'purchase_additional_consulting_hours',
    SUBMIT_QUERY: 'submit_query',
    ACCESS_AND_DOWNLOAD_PAST_PURCHASE: 'access_and_download_previous_purchases',
    PURCHASE_NEW_HR_TEMPLATES: 'purchase_new_hr_templates',
    ADD_REPLACE_HR_TEMPLATE: 'add/replace_hr_templates',
    CREATING_EDITING_ANY_USER: 'create/edit_any_user',
    CREATE_EDIT_DELETE_ROLES: 'create/edit/delete_roles',
    VIEW_USER: 'view_user_listing_page',
    LABOR_EMPLOYMENT_CONTENT: 'labor_&_employment',
    EMPLOYEE_LIFECYCLE_MANAGEMENT: 'employee_lifecycle_management',
    COMPLIANCE: 'compliance_checklist',
    INDICATORS_AND_TRENDS: 'indicators_&_trends',
    INSIGHTS_AND_ANALYSIS: 'insights_&_analysis',
    ACCESS_AND_CONTRIBUTE_HR_COMMUNITY:
      'access_&_contribute_to_hr_professional_community_membership',
    VIEW_COUNTRIES_LISTING_PAGE: 'view_countries_listing_page',
    ADD_EDIT_COUNTRIES_LISTING_PAGE: 'add/edit_countries_from_listing_page',
    CREATE_SUBSCRIPTION_PACKAGES: 'manage_subscription_packages',
    VIEW_SUBSCRIPTION_PAGE: 'view_subscription_listing_page',
    VIEW_SUBSCIPTION_DETAIL_PAGE: 'view_subscription_details_page',
    SET_SUBSCRIPTION_PRICES: 'set_subscription_prices',
    ACCESS_TO_ALL_COUNTRY_PAGES: 'access_to_all_country_pages',
    VIEW_ROLES: 'view_role_listing_page',
    FAVORITE_COUNTRIES: 'favoriting_countries',
    ADDING_EMPLOYEE_COUNTS:
      'adding_employee_counts/types_to_favorited_countries',
    ACCOUNT_LISTING_PAGE: 'view_accounts_listing_page',
    CREATE_EDIT_ACCOUNTS: "create/edit_accounts",
    ASSIGN_TO_EXPERT: "assign_to_expert",
    MANAGE_QUERY: "manage_query",
    VIEW_QUERY_MANAGEMENT_PAGE: "view_query_management_page",
    VIEW_MY_ACCOUNT_QUERIES: "view_my_account_queries",
    CLIENT_USER_FOURUM_MODERATOR: "client_user_forum_moderator",
    CLIENT_USER_FOURUM_ADMIN: "client_user_forum_admin",
    CLIENT_USER_FOURUM_MEMBER: "client_forum_member",
    EGS_USER_FOURUM_MODERATOR: "egs_user_forum_moderator",
    EGS_USER_FOURUM_ADMIN: "egs_user_forum_admin",
    EGS_USER_FOURUM_MEMBER: "egs_forum_member",
    ALERTS_LANDING_PAGE: "insights_&_analysis",
  },
  MIXPANEL_TOKEN: '85aa7395760d0d28080e868286af52e9',
  FOURM: {
    EGS_INTERL_FORUM_DEV: "https://egsflarum.thinkpalm.info:1445/",
    GLOBAL_FORUM_DEV: "https://flarum.thinkpalm.info:1445/",
    EGS_INTERL_FORUM_TESTING: "https://egsflarum.thinkpalm.info:1445/",
    GLOBAL_FORUM_TESTING: "https://flarum.thinkpalm.info:1445/",
    EGS_INTERL_FORUM_STAGING: "https://expuserforumdev.azurewebsites.net/flarum/public/ ",
    GLOBAL_FORUM_STAGING: "https://expuserforumdev-external.azurewebsites.net/flarum/public/",
    EGS_INTERL_FORUM_PRODUCTION: "https://expuserforumdev.azurewebsites.net/flarum/public/",
    GLOBAL_FORUM_PRODUCTION: "https://expuserforumdev-external.azurewebsites.net/flarum/public/"
  },

};
